// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdTDTZZC__KIdm0A-dqCWGioQ_UaKxZk',
    appId: '1:539224831697:web:4a7770ebc5d16880fab7f0',
    messagingSenderId: '539224831697',
    projectId: 'flutter-assignment-5-new',
    authDomain: 'flutter-assignment-5-new.firebaseapp.com',
    storageBucket: 'flutter-assignment-5-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOZyAtMruGhIxthhcYgoHMJCjtdAYN8w4',
    appId: '1:539224831697:android:c59f85ff13649ff3fab7f0',
    messagingSenderId: '539224831697',
    projectId: 'flutter-assignment-5-new',
    storageBucket: 'flutter-assignment-5-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPXWD9CxfDHuU0fT1h-ChwL2AxlIWTWn0',
    appId: '1:539224831697:ios:11338de84e25ebc4fab7f0',
    messagingSenderId: '539224831697',
    projectId: 'flutter-assignment-5-new',
    storageBucket: 'flutter-assignment-5-new.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignment5New',
  );

}